name: Flutter CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ¦ Setup do Flutter
        uses: flutter-actions/setup-flutter@v1
        with:
          channel: 'stable'
          version: '3.35.1'
          cache: true

      - name: ğŸ“¥ Instalar dependÃªncias
        run: flutter pub get

      - name: ğŸ” Analisar cÃ³digo
        run: flutter analyze --no-fatal-infos .

      - name: ğŸ§ª Rodar os testes
        run: flutter test --coverage
